### ISSUE TITLE
Extra data using v3 api

### ISSUE THREAD

**Issue by drc38** [hardbyte/python-evnex#2]
Suggest using the v3 api `https://client-api.evnex.io/v3/charge-points/{charger_id}` for get charger details as it makes the voltage, current and Wh register available:
```
"meter": {
                        "currentL1": 0.054,
                        "frequency": 50,
                        "power": 0,
                        "register": 1921512,
                        "updatedDate": "2022-10-02T07:15:00.000Z",
                        "voltageL1N": 239.12
                    },
```

**Comment by hardbyte** [comment]
Thanks for the suggestion, I've started adding `schema.v3` to the library. For now I'll keep both methods in the api instance.
