### ISSUE TITLE
Dependency issue after upgrading to HASS Core 2023.11.0

### ISSUE THREAD

**Issue by jamesmccarthy** [hardbyte/python-evnex#30]
I'm getting a dependency error after updating to HASS Core 2023.11.0. 

Errors:

Logger: homeassistant.util.package
Source: util/package.py:102
First occurred: 8:18:28 PM (3 occurrences)
Last logged: 8:18:46 PM

Unable to install package evnex>=0.3.5: ERROR: Cannot install evnex==0.3.5 because these package versions have conflicting dependencies. ERROR: ResolutionImpossible: for help visit https://pip.pypa.io/en/latest/topics/dependency-resolution/#dealing-with-dependency-conflicts

Logger: homeassistant.setup
Source: setup.py:185
First occurred: 8:18:46 PM (1 occurrences)
Last logged: 8:18:46 PM

Setup failed for custom integration evnex: Requirements for evnex not found: ['evnex>=0.3.5'].

**Comment by hardbyte** [comment]
Thanks for the bug report @jamesmccarthy likely it is one of the versions of these packages was in conflict with something else (another integration or HA itself):

httpx = ">=0.23,<0.26"
pycognito = "2023.5.0"
boto3 = "^1.26"
pydantic = "^1.10"
tenacity = "^8.1"

Can you see any of those in the error messages at all?

**Comment by drc38** [comment]
I expect it is httpx, I updated one of my repos to ">=0.23" dropping the upper constraint

**Comment by drc38** [comment]
Looks like httpx will be ok if you make a new release, v0.3.5 was using <0.25

**Comment by drc38** [comment]
Hi Brian @hardbyte, are you able to issue a new release please. Cheers

**Comment by hardbyte** [comment]
Done for this library, will probably need to bump the HA plugin too
