### ISSUE TITLE
Other useful functions that could be added

### ISSUE THREAD

**Issue by drc38** [hardbyte/python-evnex#4]
- [x] `POST client-api.evnex.io/v3/charge-points/{id}/commands/change-availability` - {"changeAvailabilityType": "Inoperative|Operative", "connectorId": 1}
 
- [ ] `POST? client-api.evnex.io/v3/charge-points/{id}/commands/update-firmware` - {"location": "https://s3.ap-southeast-2.amazonaws.com/firmware.evnex.io/ChargePoint_1.2.11.7e7224b_HWV0-1_Release.dfu"}
 
- [ ] `POST? client-api.evnex.io/v3/charge-points/{id}/commands/reset` - {"resetType": "Hard|Soft"}

- [x] `POST client-api.evnex.io/v2/apps/organisations/{slug}/charge-points/{id}/commands/unlock-connector` - {"connectorId": 1}

- [x] `PUT client-api.evnex.io/v2/apps/charge-points/{id}/load-management`  - {"chargingProfilePeriods": [{"limit": <=32, "start": 0-86400}],"enabled": "True|False", "units": "A", "duration": <=86400}

**Comment by drc38** [comment]
Hi Brian, have you tried this more recent api and call to set the load profile? https://docs.evnex.io/reference/putloadmanagementprofile-1

**Comment by hardbyte** [comment]
No I've only really scratched the surface. Happy to add anything to this library though - although I'll try keep the schemas from different APIs separate to handle when they are inevitably deprecated.

**Comment by hardbyte** [comment]
I'm a bit nervous about implementing/testing the firmware and reset ones! Did you find documentation?

**Comment by drc38** [comment]
Only from inspecting the evnex website scripts. I have used both functions through Ocpp without issue.

**Comment by hardbyte** [comment]
Yeah I asked evnex about the remaining two from your list:

> Reset and Update firmware only work if your role is “Admin” (it’s a user role restriction rather than a tier restriction). There aren’t many admins around that aren’t Evnex employees; most organisations get us to administer their chargers, and simply have a “Fleet Operator” user role who can view various reports across lots of chargers but otherwise doesn’t have a whole lot of access above what a “Driver” has for their individual charger. 

Given that, I don't think it makes sense to include these firmware and reset functions in `pythen-evnex`
